
DROP TABLE IF EXISTS items CASCADE;
CREATE TABLE items (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(250) NOT NULL,
  image_url VARCHAR(250) NOT NULL,
  sold BOOLEAN NOT NULL DEFAULT FALSE,
  price INTEGER NOT NULL,
  description TEXT NOT NULL,
  category INTEGER,
  created_at TIMESTAMP,
  creator_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  buyer_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
);


