DROP TABLE IF EXISTS orders CASCADE;

CREATE TABLE orders (
item_id INTEGER REFERENCES items(id) ON DELETE CASCADE NOT NULL,
buyer_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
date_bought TIMESTAMP
);
